# Generated by Django 2.0 on 2017-12-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('skills', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('skills', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SummonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('skills', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='memo',
            new_name='user_config',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='time_limit',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
