# Generated by Django 2.0 on 2017-12-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ass', '0002_auto_20171212_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_config',
            field=models.TextField(null=True),
        ),
    ]
